Repository MegviiDetection/video_analyst, pull requests merged in 2020-02, with the labels that each got.

#2 fix param of pipeline in doc
  docs/PIPELINE_API.md
Labels: documentation

#5 Travis test
  .travis.yml
  README.md
  check_format.sh
  docs/FORMATTING_INSTRUCTIONS.md
  main/test.py
  main/train.py
  videoanalyst/data/adaptor_dataset.py
  videoanalyst/data/datapipeline/datapipeline_base.py
  videoanalyst/data/dataset/builder.py
  videoanalyst/data/dataset/dataset_base.py
  videoanalyst/data/filter/filter_base.py
  videoanalyst/data/sampler/sampler_base.py
  videoanalyst/data/sampler/sampler_impl/track_pair_sampler.py
  videoanalyst/data/target/target_base.py
  videoanalyst/data/target/target_impl/utils/make_densebox_target.py
  videoanalyst/engine/monitor/monitor_base.py
  videoanalyst/engine/tester/tester_base.py
  videoanalyst/engine/trainer/trainer_base.py
  videoanalyst/model/backbone/backbone_impl/shufflenet_v2.py
  videoanalyst/model/builder.py
  videoanalyst/optim/builder.py
  videoanalyst/optim/grad_modifier/grad_modifier_base.py
  videoanalyst/pipeline/pipeline_base.py
  videoanalyst/pipeline/tracker/tracker_impl/siamfcpp_track.py
  videoanalyst/utils/path.py
Labels: bug

#10 Add minor features
  README.md
  docs/DEVELOP.md
  docs/TRAINING.md
  main/train.py
  videoanalyst/data/datapipeline/builder.py
  videoanalyst/engine/tester/tester_impl/lasot.py
  videoanalyst/engine/tester/tester_impl/vot.py
  videoanalyst/engine/trainer/trainer_impl/regular_trainer.py
  videoanalyst/evaluation/got_benchmark/experiments/lasot.py
Labels: bug, enhancement

#12 Minor changes
  demo/tools/osdet_demo_wt_got10k_image.sh
  demo/tools/osdet_demo_wt_static_image.sh
  experiments/osdet/test/siamfcpp_googlenet-osdet.yaml
  videoanalyst/data/dataset/dataset_impl/got10k.py
  videoanalyst/pipeline/tracker/tracker_impl/siamfcpp_osdet.py
Labels: enhancement
